### ISSUE TITLE
제안서 리뷰

### ISSUE THREAD

**Issue by MisooKim2** [4binzzzz/PY202309-P#1]
1. 영어로 작성해주세요.
2. 기능이 다소 부족해보입니다. 기능을 추가하거나 확장하십시오. (예: 기분에 따른 향수 추천 등)
- 변경 사항은 제안서는 수정하지 마시고, 1차 진척보고서에 반영하여 주시길 바랍니다

**Comment by 4binzzzz** [comment]
이슈 해결했습니다.

제안서 영어로 재작성후 다시 커밋하였고, 기능과 관련한 변경사항은 추후 수정하여 반영하도록 하겠습니다
